In [6]:
# importando bibliotecas
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

In [8]:
# ignorando warnings
import warnings
warnings.filterwarnings('ignore')

In [5]:
# carregando dataset
df = pd.read_csv("../data/clean.csv", sep=',', encoding='iso-8859-1')
df.set_index('Member_number', inplace=True)
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
Member_number,,,,,,,,,,,,,,,,,,,,,
1000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
1001,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,1,0,1,0,0
1002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
4998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4999,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,1,0
5000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# criando associacao
frequent_itemsets = apriori(df, min_support=0.05, use_colnames=True)
frequent_itemsets

      support                                        itemsets
0    0.078502                                      (UHT-milk)
1    0.119548                                          (beef)
2    0.079785                                       (berries)
3    0.062083                                     (beverages)
4    0.158799                                  (bottled beer)
..        ...                                             ...
160  0.050539  (tropical fruit, other vegetables, whole milk)
161  0.071832          (yogurt, other vegetables, whole milk)
162  0.065162                  (soda, rolls/buns, whole milk)
163  0.065931                (yogurt, rolls/buns, whole milk)
164  0.054387                      (whole milk, yogurt, soda)

[165 rows x 2 columns]

In [ ]:
# ordenando por suporte
frequent_itemsets.sort_values('support', ascending=False).head(10)

      support                        itemsets
55   0.458184                    (whole milk)
37   0.376603              (other vegetables)
41   0.349666                    (rolls/buns)
47   0.313494                          (soda)
56   0.282966                        (yogurt)
51   0.233710                (tropical fruit)
42   0.230631               (root vegetables)
5    0.213699                 (bottled water)
44   0.206003                       (sausage)
116  0.191380  (other vegetables, whole milk)

In [11]:
# criando regras
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(other vegetables),(beef),0.376603,0.119548,0.050795,0.134877,1.128223,0.005773,1.017719,0.182309
1,(beef),(other vegetables),0.119548,0.376603,0.050795,0.424893,1.128223,0.005773,1.083966,0.129082
2,(beef),(whole milk),0.119548,0.458184,0.064135,0.536481,1.170886,0.009360,1.168919,0.165762
3,(whole milk),(beef),0.458184,0.119548,0.064135,0.139978,1.170886,0.009360,1.023754,0.269364
4,(bottled beer),(other vegetables),0.158799,0.376603,0.068497,0.431341,1.145345,0.008692,1.096257,0.150857
...,...,...,...,...,...,...,...,...,...,...
253,"(soda, whole milk)",(yogurt),0.151103,0.282966,0.054387,0.359932,1.271999,0.011630,1.120247,0.251899
254,"(yogurt, soda)",(whole milk),0.097486,0.458184,0.054387,0.557895,1.217622,0.009720,1.225537,0.198033
255,(whole milk),"(yogurt, soda)",0.458184,0.097486,0.054387,0.118701,1.217622,0.009720,1.024073,0.329867
256,(yogurt),"(soda, whole milk)",0.282966,0.151103,0.054387,0.192203,1.271999,0.011630,1.050879,0.298223
257,(soda),"(yogurt, whole milk)",0.313494,0.150590,0.054387,0.173486,1.152042,0.007178,1.027702,0.192243

In [12]:
# ordenando por confiança
rules.sort_values('confidence', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
192,"(bottled water, other vegetables)",(whole milk),0.093894,0.458184,0.056183,0.598361,1.305941,0.013162,1.349012,0.258544
234,"(yogurt, other vegetables)",(whole milk),0.120318,0.458184,0.071832,0.597015,1.303003,0.016704,1.344507,0.264348
246,"(yogurt, rolls/buns)",(whole milk),0.111339,0.458184,0.065931,0.592166,1.292420,0.014917,1.328521,0.254605
204,"(other vegetables, rolls/buns)",(whole milk),0.146742,0.458184,0.082093,0.559441,1.220996,0.014859,1.229837,0.212124
254,"(yogurt, soda)",(whole milk),0.097486,0.458184,0.054387,0.557895,1.217622,0.009720,1.225537,0.198033
224,"(other vegetables, soda)",(whole milk),0.124166,0.458184,0.069266,0.557851,1.217528,0.012375,1.225416,0.203992
228,"(tropical fruit, other vegetables)",(whole milk),0.091329,0.458184,0.050539,0.553371,1.207749,0.008693,1.213123,0.189302
240,"(rolls/buns, soda)",(whole milk),0.119805,0.458184,0.065162,0.543897,1.187072,0.010269,1.187926,0.179041
174,(shopping bags),(whole milk),0.168291,0.458184,0.091329,0.542683,1.184422,0.014220,1.184772,0.187213
216,"(sausage, other vegetables)",(whole milk),0.092868,0.458184,0.050282,0.541436,1.181702,0.007732,1.181551,0.169504